// module.exports = require('./examples/gestures-demo/index');
// module.exports = require('./examples/helloWorld/index');
// module.exports = require('./examples/basicLayout/index');
// module.exports = require('./examples/objExample/index');
// module.exports = require('./examples/eventing/index');
// module.exports = require('./examples/twitter/index');
// module.exports = require('./examples/origin/index');
module.exports = require('./examples/LightsGL/index');
// module.exports = require('./examples/noapi/index');
